# Generated by Django 5.2.6 on 2025-09-10 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('html_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('category', models.CharField(default='', max_length=100)),
                ('content', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, default='icon/placeholder.png', null=True, upload_to='blog/images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
