# Generated by Django 5.2.6 on 2025-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='blog/documents/'),
        ),
    ]
